services:
  bolt-ai:
      image: bolt-ai:production
      build:
        context: .
        dockerfile: Dockerfile
        target: bolt-ai-production
      container_name: bolt-ai
      env_file:
        - stack.env
      networks:
        - homelabnetwork
      ports:
        - "5173:5173"
      extra_hosts:
        - "host.docker.internal:host-gateway"      
      command: pnpm run dockerstart

networks:
  homelabnetwork:
    external: true
