services:
  app-dev:
      image: bolt-ai:development
      build:
        context: .
        dockerfile: Dockerfile
        target: bolt-ai-development
      container_name: bolt-ai
      env_file:
        - stack.env
      networks:
        - homelabnetwork
      ports:
        - "5173:5173"
      extra_hosts:
        - "host.docker.internal:host-gateway"   
      volumes:
        - type: bind
          source: .
          target: /app
          consistency: cached
        - /app/node_modules   
      command: pnpm run dev --host 0.0.0.0

networks:
  homelabnetwork:
    external: true
