name: boltdiy
services:
  bolt:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    container_name: bolt-ai
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
#    networks:
#      - homelabnetwork
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "5173:5173"
    command: pnpm run dockerstart

#networks:
#  homelabnetwork:
#    external: true
