services:
  app-prebuild:
      image: ghcr.io/stackblitz-labs/bolt.diy:latest
      container_name: bolt-ai
      env_file:
        - stack.env
      networks:
        - homelabnetwork
      ports:
        - "5173:5173"
      extra_hosts:
        - "host.docker.internal:host-gateway"   

      command: pnpm run dockerstart
      profiles:
        - prebuilt

networks:
  homelabnetwork:
    external: true
